name: dghub_generator
description: "Developed by DGHub Studio"
version: 0.0.1-beta9.4
homepage: https://pub.dghub.in
repository: https://github.com/DGFlutterPub/dghub_generator
issue_tracker: https://github.com/DGFlutterPub/dghub_generator/issues

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^6.4.1
  build: ^2.4.1
  meta: ^1.15.0
  source_gen: ^1.5.0
  change_case: ^2.0.1
  mason: ^0.1.0-dev.60
  code_builder: ^4.10.0
  dart_style: ^2.3.6
  cli_completion: ^0.5.0
  pub_updater: ^0.4.0
  dio: ^5.4.3+1
  path: ^1.9.0
  args: ^2.5.0
  json_annotation: ^4.9.0
  logger: ^2.4.0
  pluralize: ^0.0.8
  checked_yaml: ^2.0.3
  cli_util: ^0.4.1
  image: ^4.2.0
  yaml: ^3.1.2
  mason_logger: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
  mockito: ^5.4.4
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
     - images/
 
executables:
  dg: