var flutterInit = [
  {
    "path": "lib/routes/routes.dart",
    "data":
        "aW1wb3J0ICdwYWNrYWdlOmF1dG9fcm91dGUvYXV0b19yb3V0ZS5kYXJ0JzsKCnBhcnQgJ3JvdXRlcy5nci5kYXJ0JzsKCi8vLS1mbHV0dGVyIHB1YiBydW4gYnVpbGRfcnVubmVyIGJ1aWxkIC0tZGVsZXRlLWNvbmZsaWN0aW5nLW91dHB1dHMKCkBBdXRvUm91dGVyQ29uZmlnKCkKY2xhc3MgUm91dGVzIGV4dGVuZHMgXyRSb3V0ZXMgewogIEBvdmVycmlkZQogIExpc3Q8QXV0b1JvdXRlPiBnZXQgcm91dGVzID0+IFsKICAgICAgICAvLyBDdXN0b21Sb3V0ZShpbml0aWFsOiB0cnVlLCBwYWdlOiBQZXJtaXNzaW9uUm91dGUucGFnZSksCiAgICAgIF07Cn0K",
    "type": "text"
  },
  {
    "path": "lib/config/global.dart",
    "data": "Y29uc3QgYmFzZVVybCA9ICcnOwo=",
    "type": "text"
  },
  {
    "path": "lib/gen/dg_generator.dart",
    "data": "Y2xhc3MgREdHZW5lcmF0b3Ige30K",
    "type": "text"
  },
  {
    "path": "lib/main.dart",
    "data":
        "aW1wb3J0ICdwYWNrYWdlOmZsdXR0ZXIvbWF0ZXJpYWwuZGFydCc7CmltcG9ydCAncGFja2FnZTpmbHV0dGVyX3JpdmVycG9kL2ZsdXR0ZXJfcml2ZXJwb2QuZGFydCc7CmltcG9ydCAncm91dGVzL3JvdXRlcy5kYXJ0JzsKaW1wb3J0ICdzeXN0ZW0vd2lkZ2V0cy9zY3JvbGwvc2Nyb2xsX2JlaGF2aW9yLmRhcnQnOwoKdm9pZCBtYWluKCkgewogIFdpZGdldHNGbHV0dGVyQmluZGluZy5lbnN1cmVJbml0aWFsaXplZCgpOwoKICB2YXIgcmVmID0gUHJvdmlkZXJDb250YWluZXIoKTsKCiAgcnVuQXBwKFVuY29udHJvbGxlZFByb3ZpZGVyU2NvcGUoY29udGFpbmVyOiByZWYsIGNoaWxkOiBjb25zdCBER0h1YkFwcCgpKSk7Cn0KCmNsYXNzIERHSHViQXBwIGV4dGVuZHMgU3RhdGVsZXNzV2lkZ2V0IHsKICBjb25zdCBER0h1YkFwcCh7c3VwZXIua2V5fSk7CgogIEBvdmVycmlkZQogIFdpZGdldCBidWlsZChCdWlsZENvbnRleHQgY29udGV4dCkgewogICAgZmluYWwgX3JvdXRlcyA9IFJvdXRlcygpOwogICAgcmV0dXJuIFByb3ZpZGVyU2NvcGUoCiAgICAgICAgY2hpbGQ6IE1hdGVyaWFsQXBwLnJvdXRlcigKICAgICAgcm91dGVyQ29uZmlnOiBfcm91dGVzLmNvbmZpZygpLAogICAgICBzY3JvbGxCZWhhdmlvcjogREdIdWJTY3JvbGxCZWhhdmlvci5zY3JvbGxCZWhhdmlvcigpLAogICAgICBidWlsZGVyOiAoY29udGV4dCwgY2hpbGQpIHsKICAgICAgICByZXR1cm4gREdIdWJTY3JvbGxCZWhhdmlvci5zY3JvbGxCdWlsZGVyV2lkZ2V0KGNoaWxkOiBjaGlsZCk7CiAgICAgIH0sCiAgICAgIGRhcmtUaGVtZTogVGhlbWVEYXRhKAogICAgICAgIHNjYWZmb2xkQmFja2dyb3VuZENvbG9yOiBDb2xvcnMuYmxhY2ssCiAgICAgICAgdXNlTWF0ZXJpYWwzOiB0cnVlLAogICAgICApLAogICAgICAvL3RoZW1lTW9kZTogdGhlbWVNb2RlLAogICAgICB0aGVtZTogVGhlbWVEYXRhKAogICAgICAgIHNjYWZmb2xkQmFja2dyb3VuZENvbG9yOiBDb2xvcnMud2hpdGUsCiAgICAgICAgdXNlTWF0ZXJpYWwzOiB0cnVlLAogICAgICApLAogICAgKSk7CiAgfQp9Cg==",
    "type": "text"
  },
  {
    "path": "lib/system/widgets/scroll/scroll_behavior.dart",
    "data":
        "aW1wb3J0ICdwYWNrYWdlOmZsdXR0ZXIvZ2VzdHVyZXMuZGFydCc7CmltcG9ydCAncGFja2FnZTpmbHV0dGVyL21hdGVyaWFsLmRhcnQnOwoKY2xhc3MgX0RHSHViU2Nyb2xsQmVoYXZpb3IgZXh0ZW5kcyBNYXRlcmlhbFNjcm9sbEJlaGF2aW9yIHsKICAvLyBPdmVycmlkZSBiZWhhdmlvciBtZXRob2RzIGFuZCBnZXR0ZXJzIGxpa2UgZHJhZ0RldmljZXMKICBAb3ZlcnJpZGUKICBTZXQ8UG9pbnRlckRldmljZUtpbmQ+IGdldCBkcmFnRGV2aWNlcyA9PiB7CiAgICAgICAgUG9pbnRlckRldmljZUtpbmQudG91Y2gsCiAgICAgICAgUG9pbnRlckRldmljZUtpbmQubW91c2UsCiAgICAgIH07Cn0KCmNsYXNzIF9BcHBCZWhhdmlvciBleHRlbmRzIFNjcm9sbEJlaGF2aW9yIHsKICBAb3ZlcnJpZGUKICBXaWRnZXQgYnVpbGRPdmVyc2Nyb2xsSW5kaWNhdG9yKAogICAgICBCdWlsZENvbnRleHQgY29udGV4dCwgV2lkZ2V0IGNoaWxkLCBTY3JvbGxhYmxlRGV0YWlscyBkZXRhaWxzKSB7CiAgICByZXR1cm4gY2hpbGQ7CiAgfQp9CgpjbGFzcyBER0h1YlNjcm9sbEJlaGF2aW9yIHsKICBzdGF0aWMgc2Nyb2xsQmVoYXZpb3IoKSA9PiBfREdIdWJTY3JvbGxCZWhhdmlvcigpOwogIHN0YXRpYyBzY3JvbGxCdWlsZGVyV2lkZ2V0KHtyZXF1aXJlZCBXaWRnZXQ/IGNoaWxkfSkgPT4gU2Nyb2xsQ29uZmlndXJhdGlvbigKICAgICAgYmVoYXZpb3I6IF9BcHBCZWhhdmlvcigpLCBjaGlsZDogY2hpbGQgPz8gY29uc3QgTWF0ZXJpYWwoKSk7Cn0K",
    "type": "text"
  },
  {
    "path": "lib/system/tools/tools.dart",
    "data": "Y2xhc3MgVG9vbHMge30=",
    "type": "text"
  },
];
